


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."is_allowed_user"() RETURNS boolean
    LANGUAGE "sql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
  select exists (
    select 1
    from public.allowed_users
    where lower(email) = lower(auth.email())
  );
$$;


ALTER FUNCTION "public"."is_allowed_user"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."allowed_users" (
    "email" "text" NOT NULL
);


ALTER TABLE "public"."allowed_users" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."app_settings" (
    "id" bigint NOT NULL,
    "key" "text",
    "value" "text",
    "updated_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."app_settings" OWNER TO "postgres";


ALTER TABLE "public"."app_settings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."app_settings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."games" (
    "id" bigint NOT NULL,
    "season_id" bigint,
    "game_number" integer NOT NULL,
    "game_date" "date",
    "opponent" "text",
    "home_away" "text",
    "game_type" "text" DEFAULT 'Regular Season'::"text",
    "first_picker" "text",
    "status" "text" DEFAULT 'Final'::"text",
    "first_goal_scorer" "text",
    "aaron_points" integer DEFAULT 0,
    "julie_points" integer DEFAULT 0,
    "winner" "text",
    "recap" "text",
    "created_at" timestamp without time zone DEFAULT "now"(),
    "nhl_game_id" "text",
    "last_synced_at" timestamp with time zone,
    "game_start_time" timestamp with time zone,
    "nhl_game_state" "text"
);


ALTER TABLE "public"."games" OWNER TO "postgres";


ALTER TABLE "public"."games" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."games_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."picks" (
    "id" bigint NOT NULL,
    "game_id" bigint,
    "owner" "text" NOT NULL,
    "pick_slot" integer NOT NULL,
    "player_name" "text" NOT NULL,
    "is_carry_forward" boolean DEFAULT false,
    "original_pick_text" "text",
    "goals" integer,
    "assists" integer,
    "points" integer,
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."picks" OWNER TO "postgres";


ALTER TABLE "public"."picks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."picks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."players" (
    "id" bigint NOT NULL,
    "player_name" "text",
    "position" "text",
    "is_active" boolean DEFAULT true,
    "updated_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."players" OWNER TO "postgres";


ALTER TABLE "public"."players" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."players_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."push_subscriptions" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_email" "text",
    "endpoint" "text" NOT NULL,
    "p256dh" "text" NOT NULL,
    "auth" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "last_seen_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."push_subscriptions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."rivalry_events" (
    "id" bigint NOT NULL,
    "game_id" bigint,
    "event_type" "text" NOT NULL,
    "event_key" "text" NOT NULL,
    "payload" "jsonb" DEFAULT '{}'::"jsonb",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."rivalry_events" OWNER TO "postgres";


ALTER TABLE "public"."rivalry_events" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rivalry_events_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."seasons" (
    "id" bigint NOT NULL,
    "season_key" "text" NOT NULL,
    "display_name" "text" NOT NULL,
    "is_active" boolean DEFAULT false,
    "aaron_final_total" integer DEFAULT 0,
    "julie_final_total" integer DEFAULT 0,
    "total_source" "text" DEFAULT 'imported'::"text",
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."seasons" OWNER TO "postgres";


ALTER TABLE "public"."seasons" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."seasons_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."allowed_users"
    ADD CONSTRAINT "allowed_users_pkey" PRIMARY KEY ("email");



ALTER TABLE ONLY "public"."app_settings"
    ADD CONSTRAINT "app_settings_key_key" UNIQUE ("key");



ALTER TABLE ONLY "public"."app_settings"
    ADD CONSTRAINT "app_settings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."games"
    ADD CONSTRAINT "games_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."games"
    ADD CONSTRAINT "games_season_id_game_number_key" UNIQUE ("season_id", "game_number");



ALTER TABLE ONLY "public"."picks"
    ADD CONSTRAINT "picks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."players"
    ADD CONSTRAINT "players_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."players"
    ADD CONSTRAINT "players_player_name_key" UNIQUE ("player_name");



ALTER TABLE ONLY "public"."push_subscriptions"
    ADD CONSTRAINT "push_subscriptions_endpoint_key" UNIQUE ("endpoint");



ALTER TABLE ONLY "public"."push_subscriptions"
    ADD CONSTRAINT "push_subscriptions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rivalry_events"
    ADD CONSTRAINT "rivalry_events_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."seasons"
    ADD CONSTRAINT "seasons_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."seasons"
    ADD CONSTRAINT "seasons_season_key_key" UNIQUE ("season_key");



ALTER TABLE ONLY "public"."picks"
    ADD CONSTRAINT "unique_pick_per_slot" UNIQUE ("game_id", "owner", "pick_slot");



CREATE INDEX "idx_games_season" ON "public"."games" USING "btree" ("season_id");



CREATE INDEX "idx_picks_game" ON "public"."picks" USING "btree" ("game_id");



CREATE UNIQUE INDEX "rivalry_events_game_event_key_uidx" ON "public"."rivalry_events" USING "btree" ("game_id", "event_key");



CREATE UNIQUE INDEX "unique_player_per_game_pick" ON "public"."picks" USING "btree" ("game_id", "player_name") WHERE (("player_name" IS NOT NULL) AND ("player_name" <> ''::"text"));



ALTER TABLE ONLY "public"."games"
    ADD CONSTRAINT "games_season_id_fkey" FOREIGN KEY ("season_id") REFERENCES "public"."seasons"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."picks"
    ADD CONSTRAINT "picks_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "public"."games"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."rivalry_events"
    ADD CONSTRAINT "rivalry_events_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "public"."games"("id") ON DELETE CASCADE;



ALTER TABLE "public"."allowed_users" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."app_settings" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "approved insert games" ON "public"."games" FOR INSERT WITH CHECK ("public"."is_allowed_user"());



CREATE POLICY "approved insert picks" ON "public"."picks" FOR INSERT WITH CHECK ("public"."is_allowed_user"());



CREATE POLICY "approved insert players" ON "public"."players" FOR INSERT WITH CHECK ("public"."is_allowed_user"());



CREATE POLICY "approved insert push subscriptions" ON "public"."push_subscriptions" FOR INSERT TO "authenticated" WITH CHECK ((("auth"."email"() = "user_email") AND "public"."is_allowed_user"()));



CREATE POLICY "approved insert seasons" ON "public"."seasons" FOR INSERT WITH CHECK ("public"."is_allowed_user"());



CREATE POLICY "approved insert settings" ON "public"."app_settings" FOR INSERT WITH CHECK ("public"."is_allowed_user"());



CREATE POLICY "approved read own push subscriptions" ON "public"."push_subscriptions" FOR SELECT TO "authenticated" USING (("auth"."email"() = "user_email"));



CREATE POLICY "approved update games" ON "public"."games" FOR UPDATE USING ("public"."is_allowed_user"()) WITH CHECK ("public"."is_allowed_user"());



CREATE POLICY "approved update picks" ON "public"."picks" FOR UPDATE USING ("public"."is_allowed_user"()) WITH CHECK ("public"."is_allowed_user"());



CREATE POLICY "approved update players" ON "public"."players" FOR UPDATE USING ("public"."is_allowed_user"()) WITH CHECK ("public"."is_allowed_user"());



CREATE POLICY "approved update push subscriptions" ON "public"."push_subscriptions" FOR UPDATE TO "authenticated" USING (("auth"."email"() = "user_email")) WITH CHECK (("auth"."email"() = "user_email"));



CREATE POLICY "approved update seasons" ON "public"."seasons" FOR UPDATE USING ("public"."is_allowed_user"()) WITH CHECK ("public"."is_allowed_user"());



CREATE POLICY "approved update settings" ON "public"."app_settings" FOR UPDATE USING ("public"."is_allowed_user"()) WITH CHECK ("public"."is_allowed_user"());



CREATE POLICY "block delete games" ON "public"."games" FOR DELETE USING (false);



CREATE POLICY "block delete picks" ON "public"."picks" FOR DELETE USING (false);



CREATE POLICY "block delete players" ON "public"."players" FOR DELETE USING (false);



CREATE POLICY "block delete seasons" ON "public"."seasons" FOR DELETE USING (false);



CREATE POLICY "block delete settings" ON "public"."app_settings" FOR DELETE USING (false);



ALTER TABLE "public"."games" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."picks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."players" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "public read games" ON "public"."games" FOR SELECT USING (true);



CREATE POLICY "public read picks" ON "public"."picks" FOR SELECT USING (true);



CREATE POLICY "public read players" ON "public"."players" FOR SELECT USING (true);



CREATE POLICY "public read rivalry events" ON "public"."rivalry_events" FOR SELECT USING (true);



CREATE POLICY "public read seasons" ON "public"."seasons" FOR SELECT USING (true);



CREATE POLICY "public read settings" ON "public"."app_settings" FOR SELECT USING (true);



ALTER TABLE "public"."push_subscriptions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."rivalry_events" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."seasons" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



REVOKE ALL ON FUNCTION "public"."is_allowed_user"() FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."is_allowed_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."is_allowed_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."is_allowed_user"() TO "service_role";



GRANT ALL ON TABLE "public"."allowed_users" TO "anon";
GRANT ALL ON TABLE "public"."allowed_users" TO "authenticated";
GRANT ALL ON TABLE "public"."allowed_users" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."app_settings" TO "anon";
GRANT SELECT,INSERT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."app_settings" TO "authenticated";
GRANT ALL ON TABLE "public"."app_settings" TO "service_role";



GRANT ALL ON SEQUENCE "public"."app_settings_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."app_settings_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."app_settings_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."games" TO "anon";
GRANT SELECT,INSERT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."games" TO "authenticated";
GRANT ALL ON TABLE "public"."games" TO "service_role";



GRANT ALL ON SEQUENCE "public"."games_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."games_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."games_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."picks" TO "anon";
GRANT SELECT,INSERT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."picks" TO "authenticated";
GRANT ALL ON TABLE "public"."picks" TO "service_role";



GRANT ALL ON SEQUENCE "public"."picks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."picks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."picks_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."players" TO "anon";
GRANT SELECT,INSERT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."players" TO "authenticated";
GRANT ALL ON TABLE "public"."players" TO "service_role";



GRANT ALL ON SEQUENCE "public"."players_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."players_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."players_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."push_subscriptions" TO "anon";
GRANT ALL ON TABLE "public"."push_subscriptions" TO "authenticated";
GRANT ALL ON TABLE "public"."push_subscriptions" TO "service_role";



GRANT ALL ON TABLE "public"."rivalry_events" TO "anon";
GRANT ALL ON TABLE "public"."rivalry_events" TO "authenticated";
GRANT ALL ON TABLE "public"."rivalry_events" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rivalry_events_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rivalry_events_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rivalry_events_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."seasons" TO "anon";
GRANT SELECT,INSERT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."seasons" TO "authenticated";
GRANT ALL ON TABLE "public"."seasons" TO "service_role";



GRANT ALL ON SEQUENCE "public"."seasons_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."seasons_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."seasons_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";







